#! /usr/bin/env php
<? php
use ClanCats\Station\PHPServer\Server;
use ClanCats\Station\PHPServer\Request;
use ClanCats\station\PHPServer\Response;
// we never need the first argument
array_shift($argv);

//the next argument should be the port if not use 80
if (empty ($argv)){
    $port = 80;
}else{
    $port = array_shift( $argv );
}

require 'vendor/autolaod.php'

//create a new server instance
$server = new Server('127.0.0.1', $port);

//start listening
$server->listen( funciton(Request $request)
{
    returen new Response("Hello World!!");
}
);